## defaults for _all_ profiles
[default]
port = 8000
limits = { json = "10MiB" }
controller_addr = "http://127.0.0.1:50004"
executor_addr = "http://127.0.0.1:50002"
local_executor_addr = "http://127.0.0.1:55556"
crypto_addr = "http://127.0.0.1:50005"
redis_addr = "redis://default:rivtower@127.0.0.1:6379"
redis_max_workers = 100
timing_internal_sec = 1
timing_batch = 50
log_level = "normal"
expire_time = 60
rough_internal = 10
crypto_type = "SM"
is_master = true

## set only when compiled in debug mode, i.e, `cargo build`
[debug]
port = 8000
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }
controller_addr = "http://127.0.0.1:50004"
executor_addr = "http://127.0.0.1:50002"
local_executor_addr = "http://127.0.0.1:55557"
crypto_addr = "http://127.0.0.1:50005"
redis_addr = "redis://default:rivtower@127.0.0.1:6379"
redis_max_workers = 512
timing_internal_sec = 1
timing_batch = 10000
stream_block_ms = 50
stream_max_count = 10000
packaged_tx_vub = 50
crypto_type = "SM"
is_master = true
log_level = "normal"
expire_time = 60
layer1_type = 0
enable_evict = true


[local_master]
port = 8000
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }
controller_addr = "http://docker.for.mac.host.internal:50004"
executor_addr = "http://docker.for.mac.host.internal:50002"
local_executor_addr = "http://test-executor:55556"
crypto_addr = "http://docker.for.mac.host.internal:50005"
redis_addr = "redis://default:rivtower@master-redis:6379"
timing_internal_sec = 1
timing_batch = 5000
log_level = "normal"
is_master = true

[local_validator]
port = 8000
## only the `json` key from `default` will be overridden; `form` will remain
limits = { json = "10MiB" }
controller_addr = "http://docker.for.mac.host.internal:50004"
executor_addr = "http://docker.for.mac.host.internal:50002"
local_executor_addr = "http://validator-executor:55556"
crypto_addr = "http://docker.for.mac.host.internal:50005"
redis_addr = "redis://default:rivtower@validator-redis:6379"
redis_max_workers = 100
timing_internal_sec = 1
timing_batch = 5000
log_level = "normal"
is_master = false

## set only when the `nyc` profile is selected
[test]
port = 8888
controller_addr = "http://127.0.0.1:50004"
executor_addr = "http://127.0.0.1:50002"
local_executor_addr = "http://127.0.0.1:55557"
crypto_addr = "http://127.0.0.1:50005"
redis_addr = "redis://default:rivtower@127.0.0.1:6379"
redis_max_workers = 512
timing_internal_sec = 1
timing_batch = 10000
stream_block_ms = 50
stream_max_count = 10000
packaged_tx_vub = 50
crypto_type = "SM"
is_master = true
log_level = "normal"
expire_time = 60
layer1_type = 0
enable_evict = false


## set only when compiled in release mode, i.e, `cargo build --release`
## don't use this secret_key! generate your own and keep it private!
[release]
port = 9001
controller_addr = "http://127.0.0.1:50004"
executor_addr = "http://127.0.0.1:50002"
crypto_addr = "http://127.0.0.1:50005"
redis_addr = "redis://default:rivtower@127.0.0.1:6379"
redis_max_workers = 100
timing_internal_sec = 1
timing_batch = 100
log_level = "critical"
is_master = true
